config = {
    0: `This letter is one Harry Kalven, Jr. sent to members of the Committee on the Role of the University in Political and Social Action.”<br><br>“This document should be read alongside the report,” Jamie Kalven told the <i>Maroon</i>. “You have a quite explicit expression of the drafters’ intentions. If we were a court interpreting a law, this would say a lot about legislative intent.”`,
    1: `“Each moment we find ourselves in will call for a slightly different reading of the report,” Kalven said.<br><br>“But the report is now often enforced through ‘administrative fiat.’ It can quickly harden into a creed.”`,
    2: `Jamie Kalven both began and ended our conversation with this phrase, emphasizing the report's invitation for ongoing discussion: "I think it's really clear that they were staking out a point of departure, and that they were quite explicitly acknowledging that there were questions and tensions between competing values that sort of in here, in the report that they were bequeathing to the future. They were expecting a kind of ongoing deliberative process."<br><br>Kalven added: “When I urge people to argue from the report, as opposed to against it, I'm suggesting going back to that point of departure and reclaiming the logic of the report.”`,
    3: `Despite its academic mission, the University has interests as a corporate entity. “There's just a bunch of housekeeping stuff that the University has to do: They have to balance the books, they have to clean the dorms,” Kalven said. “If you think about the University's role in urban renewal, which was in fairly recent history when the Kalven report was written. I think that's, again, a kind of underlying context for those passages about the University as a corporate entity. I think there's something deeply unresolved there," he said.`,
    8: `When Jamie was editing his father's book, he titled it A Worthy Tradition based on Harry Kalven, Jr 's understanding of tradition in the context of the first amendment. "The idea was that the First Amendment, as he understood it, was more than simply a body of law,” Jamie Kalven said. “It was a tradition of the society—and a living tradition as opposed to just the dead hand of tradition."`,
    9: `Speaking of the “several dangers that exist right now,” Jamie Kalven said, “One is that decision makers will simply take cover under this notion of political neutrality and/or institutional neutrality, and invoke the Kalven  report, which would be, I think, just a complete misreading of the character of the report.”<br><br>“Another danger,” Jamie Kalven added, “is to disaggregate what's going on and just address each thing, the attacks on DEI, the NIH funding, coming after foreign students who've simply exercised first amendment rights. If you think of each thing in isolation, there's the temptation to say, we can make a concession here in the interest of the institution in order to live to fight another day, that kind of logic. I actually think that's a really dangerous course.”
`,
    10: `An earlier version of the draft did not include “or the individual student,” and the published report still does not mention staff. “I think that’s the sort of thing that, if it were pointed out, it would immediately be addressed,” Jamie Kalven said. “It’s interesting, you know, as a limitation of the report as written, but it emphasizes the freedom of individuals.”

`,
    11: `Amidst student activism for divestment from Sudan, the Chicago Tribune reported that John Hope Franklin, then the only surviving member of the Committee, wrote, “We were strong in our position that the university should not jump every time that a crisis arose.” He did, however, note that the Darfur situation warranted an exception.<br><br>In a 2006 op-ed in the <i>Maroon</i> titled “Unfinished business of the Kalven Report,” Jamie Kalven cited Franklin’s position: “It is telling, though, that the one surviving member of the Kalven Committee, Professor John Hope Franklin, has unequivocally stated that ‘the desperate situation in Darfur is so tragic that it qualifies as the exceptional instance where I have no difficulty in concluding that divestment is consistent with the core values of our report and the mission of the University.’”
`,
    12: `Kalven distinguished between bravery as an individual characteristic and courage as "a social virtue." He emphasized the importance of "the solidarity of the shaken," a phrase coined by Czech philosopher Jan Patocka, a political dissident against the Communist Party in Czechoslovakia. Now more than ever, we must keep our values visible to one another, Kalven said.`,
    13: `This passage has a different tenor than other sections, which are encircled by caveats. Indicating the use of "obligation" in talking about actively defending the University's values, Kalven called this "very close to stating a moral imperative."
`,
    14: `The term “presumption” is a legal assumption that a fact is true based on other known quantities. Jamie Kalven emphasized his father’s thinking as a legal scholar. “In can imagine him thinking of it as a sort of common law process… where you’re sort of continuously refining a principle, deepening it, and testing it against those sort of practical challenges presented by different fact situations.”
`,
    15: `“Something else that has been effectively raised recently is an important distinction between discussion and deliberation,” referring to arguments from associate professor of philosophy and deputy dean of the Humanities Division Anton Ford. “You can talk all day about whatever, but what feels to me missing is some kind of deliberative process. And it’s not sufficient to say that the nature of the university is such that we can’t put everything up to vote—that's sort of a straw man, because there are other deliberative forms.”
`,
    16: `“There’s a kind of delicacy that is apparent in the document and the surrounding correspondence—a delicacy of managing tensions within the Committee,” Jamie Kalven said when asked about the special comment. “It’s pretty clear that Stiegler has taken the position that the University should have complete and absolute freedom to act in its corporate capacity. There should be no exceptions allowed.”<br><br>“Stigler’s position illuminates what the Committee ultimately landed on as a formulation, but I think the other point you could make about it is in terms of the way the University has applied it over the years, it might be called the Stigler Report rather than the Kalven Report.” 
`
};

sessionStorage.setItem('config', JSON.stringify(config));
