config = {
    17: `This letter is one that Harry Kalven Jr. sent to members of the Committee on the Role of the University in Political and Social Action.<br><br>“This document should be read alongside the report,” Jamie Kalven told the <i>Maroon</i>. “You have a quite explicit expression of the drafters’ intentions. If we were a court interpreting a law, this would say a lot about legislative intent.”`,
    1: `“Each moment we find ourselves in will call for a slightly different reading of the report,” Jamie Kalven said.<br><br>“But the report is now often enforced through ‘administrative fiat.’ It can quickly harden into a creed.”`,
    2: `Jamie Kalven both began and ended our conversation with this phrase, emphasizing the report's invitation for ongoing discussion: “I think it’s really clear that they were staking out a point of departure, and that they were quite explicitly acknowledging that there were questions and tensions between competing values… in the report that they were bequeathing to the future. They were expecting a kind of ongoing deliberative process.”<br><br>Kalven added: “When I urge people to argue from the report, as opposed to against it, I'm suggesting going back to that point of departure and reclaiming the logic of the report.”`,
    3: `Despite its academic mission, the University has interests as a corporate entity. “There's just a bunch of housekeeping stuff that the University has to do. They have to balance the books, they have to clean the dorms,” Jamie Kalven said. “If you think about the University's role in urban renewal, which was in fairly recent history when the Kalven Report was written, I think that's, again, a kind of underlying context for those passages about the University as a corporate entity. I think there's something deeply unresolved there,” he said.`,
    4: `The report leaves ambiguous the distinction between academic freedom and freedom of speech.<br><br>“I see it as this kind of vessel that contains certain statements with clarity and then contains within it all sorts of tensions between competing values and contains within it questions that the drafters didn't foresee,” Jamie Kalven said.<br><br>“There are things under First Amendment law that are protected, not so much because they're thought to be of intrinsic value to us as individuals or to the society, but because we don't trust the state as a censor, that's a different logic than how we organize ourselves as a university community to maximize intellectual autonomy and freedom,” Kalven added.
`,
    5: `“I'm also struck that the Committee, early in the report, is ticking off the various occasions when the University has taken some kind of action, much of it in the context of the McCarthy-era incursions on higher education,” Jamie Kalven told the <i>Maroon</i>.<br><br>The Broyles Bill inquiry refers to Illinois senator Paul Broyles’s commission investigating Communist influence in the state. The Commission held hearings about UChicago professors' political actions, during which University-funded legal representatives <a href = "https://freeexpression.uchicago.edu/history/">accompanied</a> students and faculty members. Then-University chancellor Robert Maynard Hutchins called the proceedings “unconstitutional and un-American.”<br><br>The Senate Internal Security Committee, chaired by Indiana Senator William E. Jenner, accused faculty at UChicago and other universities of involvement in Communist and subversive committees.<br><br>The National Defense Education Act of 1958 required any student who applied for a federal loan under the act to sign a loyalty oath and make an affidavit stating that they did not support any organization that encouraged an illegal overthrow of the U.S. government. 
`,
    6: `“My understanding,” Jamie Kalven said, “is there was a student sit-in—including Bernie Sanders, who was an undergraduate here—in response to which the University changed some discriminatory rental policies. Nobody's made much of that as a precedent, but doesn't that suggest at least one instance where there was a direct challenge to the practices of the University as a corporate entity in the broader neighborhood that was successful?”
`,
    7: `“In 1967, student activism is now building to a crescendo on the U of C campus and elsewhere,” Jamie Kalven explained. “I think there were multiple issues, but one of the most salient issues at the time was whether it was appropriate for the University to cooperate with the Selective Service, with the draft, which was a matter of really urgent personal concern for male students.” In addition to the anti-Vietnam War movement, Kalven noted “the beginnings of stirrings of activism addressed to apartheid in South Africa.”`,
    8: `When Jamie was editing his father's book, he titled it <i>A Worthy Tradition</i> based on Harry Kalven Jr. 's understanding of tradition in the context of the First Amendment. “The idea was that the First Amendment, as he understood it, was more than simply a body of law,” Jamie Kalven said. “It was a tradition of the society—and a living tradition—as opposed to just the dead hand of tradition.”`,
    9: `Speaking on the “several dangers that exist right now,” Jamie Kalven said, “One is that decision makers will simply take cover under this notion of political neutrality and/or institutional neutrality, and invoke the Kalven Report, which would be, I think, just a complete misreading of the character of the report.”<br><br>“Another danger,” Kalven added, “is to disaggregate what's going on and just address each thing, the attacks on DEI, the NIH funding, coming after foreign students who've simply exercised First Amendment rights. If you think of each thing in isolation, there's the temptation to say, ‘We can make a concession here in the interest of the institution in order to live to fight another day,’ that kind of logic. I actually think that's a really dangerous course.”
`,
    10: `An earlier version of the draft did not include “or the individual student,” and the published report still does not mention staff. “I think that’s the sort of thing that, if it were pointed out, it would immediately be addressed,” Jamie Kalven said. “It’s interesting, you know, as a limitation of the report as written, but it emphasizes the freedom of individuals.”

`,
    11: `Amidst student activism for divestment from Sudan, the <i>Chicago Tribune</i> reported that John Hope Franklin, then the only surviving member of the Committee, <a href = "https://www.chicagotribune.com/2007/02/08/university-stands-pat-activists-take-aim">wrote</a>, “We were strong in our position that the university should not jump every time that a crisis arose.” He did, however, note that the Darfur situation warranted an exception.<br><br>In a 2006 op-ed in the *Maroon* titled “Unfinished business of the Kalven Report,” Jamie Kalven <a href = "https://chicagomaroon.com/7464/viewpoints/op-ed/unfinished-business-of-the-kalven-report/">cited</a> Franklin’s position: “It is telling, though, that the one surviving member of the Kalven Committee, Professor John Hope Franklin, has unequivocally stated that ‘the desperate situation in Darfur is so tragic that it qualifies as the exceptional instance where I have no difficulty in concluding that divestment is consistent with the core values of our report and the mission of the University.’”
`,

    12: `Kalven distinguished between bravery as an individual characteristic and courage as “a social virtue.” He emphasized the importance of “the solidarity of the shaken,” a phrase coined by Czech philosopher Jan Patočka, a political dissident against the Communist Party in Czechoslovakia. “We must keep our values visible to one another,” Kalven said.`,
    13: `This passage has a different tenor than other sections, which are encircled by caveats. Indicating the use of “obligation” in talking about actively defending the University's values, Kalven called this “very close to stating a moral imperative.”
`,
    14: `The term “presumption” is a legal assumption that a fact is true based on other known quantities. Jamie Kalven emphasized his father’s thinking as a legal scholar: “I can imagine him thinking of it as a sort of common law process… where you’re sort of continuously refining a principle, deepening it, and testing it against those sorts of practical challenges presented by different fact situations.”
`,
    15: `“Something else that has been effectively raised recently is an important distinction between discussion and deliberation,” <a href = "https://www.chronicle.com/article/the-chicago-principles-are-undemocratic">referring</a> to arguments from associate professor of philosophy and deputy dean of the Humanities Division Anton Ford. “You can talk all day about whatever, but what feels to me missing is some kind of deliberative process. And it’s not sufficient to say that the nature of the University is such that we can’t put everything up to vote—that's sort of a straw man, because there are other deliberative forms.”
`,

    16: `“There’s a kind of delicacy that is apparent in the document and the surrounding correspondence—a delicacy of managing tensions within the Committee,” Jamie Kalven said when asked about the special comment. “It’s pretty clear that Stiegler has taken the position that the University should have complete and absolute freedom to act in its corporate capacity. There should be no exceptions allowed.”<br><br>“Stigler’s position illuminates what the Committee ultimately landed on as a formulation, but I think the other point you could make about it is in terms of the way the University has applied it over the years, it might be called the Stigler Report rather than the Kalven Report.”
`
};

sessionStorage.setItem('config', JSON.stringify(config));
