{
  "title": "Class Clowned",
  "by": "Daniel Ruttenberg",
  "clues": [
    { "d":"A", "n":1, "x":0, "y":0, "a":"FLAW", "c":"Characteristic of a Shakespearean character" },
    { "d":"A", "n":5, "x":5, "y":0, "a":"FLEX", "c":"Show your veinity?" },
    { "d":"A", "n":9, "x":10, "y":0, "a":"PATER", "c":"Julius, to Caesarion" },
    { "d":"A", "n":14, "x":0, "y":1, "a":"MOMENTARY", "c":"Brief" },
    { "d":"A", "n":16, "x":10, "y":1, "a":"ATONE", "c":"Say 10 hail mary's and 5 our fathers, for instance" },
    { "d":"A", "n":17, "x":0, "y":2, "a":"RADIOLOGY", "c":"Class on NPR?" },
    { "d":"A", "n":18, "x":10, "y":2, "a":"KINDA", "c":"Hesitant \"yes\"" },
    { "d":"A", "n":19, "x":0, "y":3, "a":"INALL", "c":"It starts a conclusion after all" },
    { "d":"A", "n":20, "x":9, "y":3, "a":"LILTED", "c":"Played a light tune" },
    { "d":"A", "n":21, "x":3, "y":4, "a":"LABORHISTORY", "c":"Class on 20th century obstetricians?" },
    { "d":"A", "n":26, "x":0, "y":5, "a":"ZAS", "c":"Pies, informally" },
    { "d":"A", "n":29, "x":4, "y":5, "a":"WIPEOUT", "c":"ABC TV show hosted by John Henson and John Anderson" },
    { "d":"A", "n":30, "x":0, "y":6, "a":"OPEC", "c":"Oil org." },
    { "d":"A", "n":32, "x":5, "y":6, "a":"DEBT", "c":"Economic talking point" },
    { "d":"A", "n":33, "x":10, "y":6, "a":"AFTER", "c":"Like a photo of a person in too-big jeans" },
    { "d":"A", "n":38, "x":0, "y":7, "a":"NEPAL", "c":"Hillary destination" },
    { "d":"A", "n":40, "x":6, "y":7, "a":"RED", "c":"Like the letter A in a Hawthorne novel" },
    { "d":"A", "n":41, "x":10, "y":7, "a":"NARDO", "c":"\"Taxi\" character" },
    { "d":"A", "n":42, "x":0, "y":8, "a":"EXTRA", "c":"Easy part for actors to get" },
    { "d":"A", "n":43, "x":6, "y":8, "a":"AKAL", "c":"Immortal, to Sikhs" },
    { "d":"A", "n":45, "x":11, "y":8, "a":"QUIT", "c":"Cease"},
    { "d":"A", "n":46, "x":4, "y":9, "a":"MANATEE", "c":"Sea cow" },
    { "d":"A", "n":49, "x":12, "y":9, "a":"ETA", "c":"AA Calculation" },
    { "d":"A", "n":50, "x":0, "y":10, "a":"NUMBERTHEORY", "c":"Class on picking up women?" },
    { "d":"A", "n":55, "x":0, "y":11, "a":"ORIENT", "c":"Location of an Agatha Christie novel" },
    { "d":"A", "n":56, "x":10, "y":11, "a":"EASES", "c":"Relaxes" },
    { "d":"A", "n":60, "x":0, "y":12, "a":"HINGE", "c":"Depend (on)" },
    { "d":"A", "n":61, "x":6, "y":12, "a":"FRENCHART", "c":"Class on Klimt and Eisenstaedt?" },
    { "d":"A", "n":65, "x":0, "y":13, "a":"INCAS", "c":"Ancient Peruvians" },
    { "d":"A", "n":66, "x":6, "y":13, "a":"MYANTONIA", "c":"Final book in series which includes \"O Pioneers!\"" },
    { "d":"A", "n":67, "x":0, "y":14, "a":"TEENS", "c":"One Direction fans, perhaps" },
    { "d":"A", "n":68, "x":6, "y":14, "a":"LURE", "c":"Get in the door" },
    { "d":"A", "n":69, "x":11, "y":14, "a":"OKAY", "c":"Worth six out of ten stars" },
   
    { "d":"D", "n":1, "x":0, "y":0, "a":"FMRI", "c":"Detector of brain activity" },
    { "d":"D", "n":2, "x":1, "y":0, "a":"LOAN", "c":"College credit?" },
    { "d":"D", "n":3, "x":2, "y":0, "a":"AMDA", "c":"Heather's \"Melrose Place\" role" },
    { "d":"D", "n":4, "x":3, "y":0, "a":"WEILL", "c":"\"Mack the Knife\" composer" },
    { "d":"D", "n":5, "x":5, "y":0, "a":"FTL", "c":"\"This sucks!\" (Acronym)"},
    { "d":"D", "n":6, "x":6, "y":0, "a":"LAO", "c":"___ Tzu, Chinese philosopher" },
    { "d":"D", "n":7, "x":7, "y":0, "a":"ERG", "c":"Energy unit" },
    { "d":"D", "n":8, "x":8, "y":0, "a":"XYY", "c":"Syndrome causing one to have 47 chromosomes but no notable phenotypic difference" },
    { "d":"D", "n":9, "x":10, "y":0, "a":"PAKISTAN", "c":"Acronym of five regions of the British Raj" },
    { "d":"D", "n":10, "x":11, "y":0, "a":"ATILT", "c":"Off" },
    { "d":"D", "n":11, "x":12, "y":0, "a":"TONTO", "c":"\"Lone Ranger\" companion" },
    { "d":"D", "n":12, "x":13, "y":0, "a":"ENDER", "c":"Card part?" },
    { "d":"D", "n":13, "x":14, "y":0, "a":"READY", "c":"Prepared" },
    { "d":"D", "n":15, "x":4, "y":1, "a":"NOLAW", "c":"\"Congress shall make ___...\" (Bill of Rights)" },
    { "d":"D", "n":20, "x":9, "y":3, "a":"LIU", "c":"Lucy of \"Charlie's Angels\"" },
    { "d":"D", "n":22, "x":5, "y":4, "a":"BID", "c":"Auction action" },
    { "d":"D", "n":23, "x":6, "y":4, "a":"OPERANT", "c":"At work" },
    { "d":"D", "n":24, "x":7, "y":4, "a":"REBEKAH", "c":"Jacob's mom" },
    { "d":"D", "n":25, "x":8, "y":4, "a":"HOTDATE", "c":"Casanova Event" },
    { "d":"D", "n":26, "x":0, "y":5, "a":"ZONE", "c":"Dimension" },
    { "d":"D", "n":27, "x":1, "y":5, "a":"APEX", "c":"Tournament won by PPMD in 2015" },
    { "d":"D", "n":28, "x":2, "y":5, "a":"SEPT", "c":"Mo. that kicks off school" },
    { "d":"D", "n":31, "x":3, "y":6, "a":"CAR", "c":"\"Chitty Chitty Bang Bang\" vehicle" },
    { "d":"D", "n":34, "x":11, "y":6, "a":"FAQ", "c":"Web site section, initially" },
    { "d":"D", "n":35, "x":12, "y":6, "a":"TRUE", "c":"T on a test" },
    { "d":"D", "n":36, "x":13, "y":6, "a":"EDIT", "c":"Remedy, as an essay" },
    { "d":"D", "n":37, "x":14, "y":6, "a":"ROTA", "c":"\"The Godfather\" composer Nino" },
    { "d":"D", "n":39, "x":4, "y":7, "a":"LAMENESS", "c":"Quality of a 50-something to a 20-something" },
    { "d":"D", "n":44, "x":9, "y":8, "a":"LEO", "c":"August animal" },
    { "d":"D", "n":47, "x":5, "y":9, "a":"ART", "c":"Singer-songwriter Garfunkel" },
    { "d":"D", "n":48, "x":10, "y":9, "a":"ERECT", "c":"Build" },
    { "d":"D", "n":50, "x":0, "y":10, "a":"NOHIT", "c":"Like a perfect game for Nolan Ryan" },
    { "d":"D", "n":51, "x":1, "y":10, "a":"URINE", "c":"Fluid in the title of a Tony-winning 2001 musical" },
    { "d":"D", "n":52, "x":2, "y":10, "a":"MINCE", "c":"Prepare pork for sausage" },
    { "d":"D", "n":53, "x":3, "y":10, "a":"BEGAN", "c":"Crossed the starting line" },
    { "d":"D", "n":54, "x":11, "y":10, "a":"YAHOO", "c":"Google competitor" },
    { "d":"D", "n":57, "x":12, "y":11, "a":"SANK", "c":"Pulled a \"Titanic\"" },
    { "d":"D", "n":58, "x":13, "y":11, "a":"ERIA", "c":"Suffix meaning \"place of business\"" },
    { "d":"D", "n":59, "x":14, "y":11, "a":"STAY", "c":"2012 Rihanna song" },
    { "d":"D", "n":61, "x":6, "y":12, "a":"FML", "c":"\"This sucks!\" (Acronym)"},
    { "d":"D", "n":62, "x":7, "y":12, "a":"RYU", "c":"\"Street Fighter\" fighter"},
    { "d":"D", "n":63, "x":8, "y":12, "a":"EAR", "c":"2-down, to Shakespeare"},
    { "d":"D", "n":64, "x":9, "y":12, "a":"NNE", "c":"Bos., to NYC"}
  ]
}
