// Initialize auth - see https://theoephraim.github.io/node-google-spreadsheet/#/guides/authentication
const serviceAccountAuth = new JWT({
    // env var values here are copied from service account credentials generated by google
    // see "Authentication" section in docs for more info
    email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,
    key: process.env.GOOGLE_PRIVATE_KEY,
    scopes: ['https://www.googleapis.com/auth/spreadsheets']
});

const doc = new GoogleSpreadsheet(
    '1bhl7nXFpEDFdrfQ4L-2l2fhTIjxAjwTn1UXO-K7ER1Q',
    serviceAccountAuth
);

// loads document properties and worksheets
await doc.loadInfo();
console.log(doc.title);
await doc.updateProperties({ title: 'renamed doc' });

// or use `doc.sheetsById[id]` or `doc.sheetsByTitle[title]`
const sheet = doc.sheetsByIndex[0];
console.log(sheet.title);
console.log(sheet.rowCount);

// adding / removing sheets
const newSheet = await doc.addSheet({ title: 'another sheet' });
await newSheet.delete();

const rows = await sheet.getRows();
