{
  "title": "Table Talk",
  "by": "Daniel Ruttenberg",
  "clues": [
    { "d":"A", "n":1, "x":0, "y":0, "a":"ATE", "c":"Oil grp." },
    { "d":"A", "n":5, "x":4, "y":0, "a":"ENAMI", "c":"Ruiner of a perfect GPA" },
    { "d":"A", "n":9, "x":10, "y":0, "a":"STRIP", "c":"Get rid of graphite" },
    { "d":"A", "n":14, "x":0, "y":1, "a":"FAX", "c":"Edible fish" },
    { "d":"A", "n":15, "x":4, "y":1, "a":"GOFAR", "c":"Give stars" },
    { "d":"A", "n":16, "x":10, "y":1, "a":"ERIKA", "c":"Au pair" },
    { "d":"A", "n":17, "x":0, "y":2, "a":"GOODGRADE", "c":"Ailment healed by ice cream, or 1 & 2" },
    { "d":"A", "n":19, "x":10, "y":2, "a":"CANER", "c":"Love, for Napoleon" },
    { "d":"A", "n":20, "x":3, "y":3, "a":"ASTRA", "c":"Where some burials take place" },
    { "d":"A", "n":21, "x":10, "y":3, "a":"TVDAD", "c":"\"___ Touch, but you gotta keep your head held high\", or 3 & 4 (3 words)" },
    { "d":"A", "n":23, "x":0, "y":4, "a":"SHIH", "c":"Model Reid" },
    { "d":"A", "n":25, "x":7, "y":4, "a":"MOI", "c":"Skin growth" },
    { "d":"A", "n":26, "x":11, "y":4, "a":"ESSO", "c":"Members of the \"Bounty,\" for instance" },
    { "d":"A", "n":29, "x":0, "y":5, "a":"CABLECHANNEL", "c":"Leaf through" },
    { "d":"A", "n":34, "x":0, "y":6, "a":"ABS", "c":"Rainbow's shape" },
    { "d":"A", "n":35, "x":4, "y":6, "a":"CHA", "c":"Child star O'Neal" },
    { "d":"A", "n":38, "x":8, "y":6, "a":"ESP", "c":"Blemishes, for a car" },
    { "d":"A", "n":39, "x":12, "y":6, "a":"LBJ", "c":"Bridal accessory" },
    { "d":"A", "n":41, "x":0, "y":7, "a":"PEE", "c":"Straightforward, or 5 & 6 " },
    { "d":"A", "n":43, "x":4, "y":7, "a":"ORN", "c":"Smartphones, e.g. " },
    { "d":"A", "n":44, "x":8, "y":7, "a":"CIS", "c":"Key above \"shift\""},
    { "d":"A", "n":46, "x":12, "y":7, "a":"OYE", "c":"Star of the ball" },
    { "d":"A", "n":48, "x":0, "y":8, "a":"ERN", "c":"Elizabethan ___" },
    { "d":"A", "n":49, "x":4, "y":8, "a":"NON", "c":"The Wright brothers' Ohio home" },
    { "d":"A", "n":51, "x":8, "y":8, "a":"ATO", "c":"\"On ___\" (work of 37-Down)" },
    { "d":"A", "n":53, "x":12, "y":8, "a":"REL", "c":"Comfy furniture" },
    { "d":"A", "n":56, "x":3, "y":9, "a":"ROMANNUMERAL", "c":"Component of brainstem" },
    { "d":"A", "n":57, "x":0, "y":10, "a":"ASME", "c":"\"Breaking Bad\" setting, or 7 & 8 (2 words)" },
    { "d":"A", "n":62, "x":5, "y":10, "a":"EHE", "c":"Dealing with birth" },
    { "d":"A", "n":65, "x":11, "y":10, "a":"AERO", "c":"\"The ___ Guys\" (2010 action movie)" },
    { "d":"A", "n":66, "x":0, "y":11, "a":"ALOUD", "c":"Silly arm component, or 9 & 10 (2 words)" },
    { "d":"A", "n":68, "x":7, "y":11, "a":"LIMOS", "c":"Japanese cartoons" },
    { "d":"A", "n":69, "x":0, "y":12, "a":"RUMBA", "c":"Engrave" },
    { "d":"A", "n":70, "x":6, "y":12, "a":"BLOODTYPE", "c":"Oodles" },
    { "d":"A", "n":71, "x":0, "y":13, "a":"ORMER", "c":"Disliked fervently" },
    { "d":"A", "n":72, "x":6, "y":13, "a":"CITED", "c":"Sew a falcon's eyes shut" },
    { "d":"A", "n":73, "x":12, "y":13, "a":"ATM", "c":"Manipulate text" },
   
   
    { "d":"D", "n":1, "x":0, "y":0, "a":"AFG", "c":"Job safety org." },
    { "d":"D", "n":2, "x":1, "y":0, "a":"TAO", "c":"Homer's occupation" },
    { "d":"D", "n":3, "x":2, "y":0, "a":"EXO", "c":"Feature of constitution and scrunchie" },
    { "d":"D", "n":4, "x":4, "y":0, "a":"EGGS", "c":"Breakfast advertised by a rabbit or a leprechaun" },
    { "d":"D", "n":5, "x":5, "y":0, "a":"NORT", "c":"\"Is it a boy ___ girl?\" (2 words)"},
    { "d":"D", "n":6, "x":6, "y":0, "a":"AFAR", "c":"Salt, to a chemist" },
    { "d":"D", "n":7, "x":7, "y":0, "a":"MADAMA", "c":"Strong work ___ (diligence)" },
    { "d":"D", "n":8, "x":8, "y":0, "a":"IRE", "c":"Buff" },
    { "d":"D", "n":9, "x":10, "y":0, "a":"SECT", "c":"Made a law" },
    { "d":"D", "n":10, "x":11, "y":0, "a":"TRAVEL", "c":"Avatar of Vishnu" },
    { "d":"D", "n":11, "x":12, "y":0, "a":"RINDS", "c":"Soon, to Shakespeare" },
    { "d":"D", "n":12, "x":13, "y":0, "a":"IKEAS", "c":"Overlook, as an Oscar" },
    { "d":"D", "n":13, "x":14, "y":0, "a":"PARDO", "c":"Brontë's Jane" },
    { "d":"D", "n":18, "x":3, "y":2, "a":"DAHL", "c":"Clairvoyant's cards" },
    { "d":"D", "n":22, "x":0, "y":4, "a":"SCAPE", "c":"Power to read minds, for short" },
    { "d":"D", "n":24, "x":1, "y":4, "a":"HABER", "c":"Egyptian or Saudi" },
    { "d":"D", "n":26, "x":2, "y":4, "a":"IBSEN", "c":"Like a born-again Christian" },
    { "d":"D", "n":27, "x":8, "y":4, "a":"ONECAN", "c":"Stadium" },
    { "d":"D", "n":28, "x":9, "y":4, "a":"INSITU", "c":"Pierce" },
    { "d":"D", "n":30, "x":4, "y":5, "a":"ECONO", "c":"Dem.'s rival" },
    { "d":"D", "n":31, "x":5, "y":5, "a":"CHROME", "c":"\"Got it?\" reply" },
    { "d":"D", "n":32, "x":6, "y":5, "a":"HANNAH", "c":"First space on some game boards" },
    { "d":"D", "n":33, "x":10, "y":5, "a":"EPSOM", "c":"English assignment" },
    { "d":"D", "n":36, "x":12, "y":6, "a":"LORRE", "c":"Exploit" },
    { "d":"D", "n":37, "x":13, "y":6, "a":"BYEAR", "c":"Philosopher John Stuart" },
    { "d":"D", "n":40, "x":14, "y":6, "a":"JELLO", "c":"Permit" },
    { "d":"D", "n":42, "x":3, "y":9, "a":"REUBEN", "c":"Short video" },
    { "d":"D", "n":45, "x":7, "y":9, "a":"NELLIE", "c":"Like a color of makeup (2 words)" },
    { "d":"D", "n":47, "x":11, "y":9, "a":"EAST", "c":"Key material" },
    { "d":"D", "n":50, "x":0, "y":10, "a":"AARON", "c":"Goddess of night" },
    { "d":"D", "n":52, "x":1, "y":10, "a":"SLURS", "c":"Allow" },
    { "d":"D", "n":54, "x":2, "y":10, "a":"MOMMY", "c":"Marching band instruments " },
    { "d":"D", "n":55, "x":4, "y":11, "a":"DARC", "c":"Like the angles of an equilateral triangle" },
    { "d":"D", "n":57, "x":8, "y":11, "a":"IOTA", "c":"Biblical zookeeper" },
    { "d":"D", "n":58, "x":9, "y":11, "a":"MOET", "c":"Italian erupter" },
    { "d":"D", "n":59, "x":10, "y":11, "a":"ODDS", "c":"Iota" },
    { "d":"D", "n":60, "x":6, "y":12, "a":"BCS", "c":"\"Dank\" internet fad" },
    { "d":"D", "n":61, "x":12, "y":12, "a":"YAY", "c":"A single time" },
    { "d":"D", "n":63, "x":13, "y":12, "a":"PTO", "c":"Opposing" },
    { "d":"D", "n":64, "x":14, "y":12, "a":"EMU", "c":"\"___ we forget\" (Kipling)"},
    { "d":"D", "n":67, "x":14, "y":12, "a":"EMU", "c":"Bruins' gp." }
  ]
}
