{
  "title": "Table Talk",
  "by": "Daniel Ruttenberg",
  "clues": [
    { "d":"A", "n":1, "x":0, "y":0, "a":"ATE", "c":"Consumed" },
    { "d":"A", "n":5, "x":4, "y":0, "a":"ENAMI", "c":"As a friend, in French" },
    { "d":"A", "n":9, "x":10, "y":0, "a":"STRIP", "c":"Get closer to a birthday suit" },
    { "d":"A", "n":14, "x":0, "y":1, "a":"FAX", "c":"Common office machine" },
    { "d":"A", "n":15, "x":4, "y":1, "a":"GOFAR", "c":"Succeed (2 words)" },
    { "d":"A", "n":16, "x":10, "y":1, "a":"ERIKA", "c":"Christensen of \"Parenthood\"" },
    { "d":"A", "n":17, "x":0, "y":2, "a":"GOODGRADE", "c":"*Nerd's objective" },
    { "d":"A", "n":19, "x":10, "y":2, "a":"CANER", "c":"Chair craftsperson" },
    { "d":"A", "n":20, "x":3, "y":3, "a":"ASTRA", "c":"'Ad -- per aspera' (Kansas' motto)" },
    { "d":"A", "n":21, "x":10, "y":3, "a":"TVDAD", "c":"Danny Tanner or Homer Simpson, for one (2 words)" },
    { "d":"A", "n":23, "x":0, "y":4, "a":"SHIH", "c":"___ Tzu: Tibetan dog " },
    { "d":"A", "n":25, "x":7, "y":4, "a":"MOI", "c":"Reply from Miss Piggy " },
    { "d":"A", "n":26, "x":11, "y":4, "a":"ESSO", "c":"Sylvan ___ (Indie pop duo)" },
    { "d":"A", "n":29, "x":0, "y":5, "a":"CABLECHANNEL", "c":"*Station that costs extra" },
    { "d":"A", "n":34, "x":0, "y":6, "a":"ABS", "c":"They may be on a bodybuilder's profile picture" },
    { "d":"A", "n":35, "x":4, "y":6, "a":"CHA", "c":"\"Don't ___\": 2005 R&B hit" },
    { "d":"A", "n":38, "x":8, "y":6, "a":"ESP", "c":"6th Sense" },
    { "d":"A", "n":39, "x":12, "y":6, "a":"LBJ", "c":"JFK successor" },
    { "d":"A", "n":41, "x":0, "y":7, "a":"PEE", "c":"Urine, informally " },
    { "d":"A", "n":43, "x":4, "y":7, "a":"ORN", "c":"Piers Anthony novel (or a Cockney's bugle) " },
    { "d":"A", "n":44, "x":8, "y":7, "a":"CIS", "c":"Not trans. " },
    { "d":"A", "n":46, "x":12, "y":7, "a":"OYE", "c":"'___ of little faith!' (2 words)" },
    { "d":"A", "n":48, "x":0, "y":8, "a":"ERN", "c":"Suffix with north or south " },
    { "d":"A", "n":49, "x":4, "y":8, "a":"NON", "c":"___ sequitur " },
    { "d":"A", "n":51, "x":8, "y":8, "a":"ATO", "c":"From ___ Z (2 words) " },
    { "d":"A", "n":53, "x":12, "y":8, "a":"REL", "c":"Theologian's subj. " },
    { "d":"A", "n":56, "x":3, "y":9, "a":"ROMANNUMERAL", "c":"*Sicilian digit " },
    { "d":"A", "n":57, "x":0, "y":10, "a":"ASME", "c":"\"You're almost as good ___\" (Cocky retort) (2 words) " },
    { "d":"A", "n":62, "x":5, "y":10, "a":"EHE", "c":"Before in Berlin" },
    { "d":"A", "n":65, "x":11, "y":10, "a":"AERO", "c":"Prefix from the Greek for \"air\"" },
    { "d":"A", "n":66, "x":0, "y":11, "a":"ALOUD", "c":"Audibly" },
    { "d":"A", "n":68, "x":7, "y":11, "a":"LIMOS", "c":"Prom Vehicles" },
    { "d":"A", "n":69, "x":0, "y":12, "a":"RUMBA", "c":"Afro-Cuban dance" },
    { "d":"A", "n":70, "x":6, "y":12, "a":"BLOODTYPE", "c":"*Important medical information" },
    { "d":"A", "n":71, "x":0, "y":13, "a":"ORMER", "c":"Abalone, by another name" },
    { "d":"A", "n":72, "x":6, "y":13, "a":"CITED", "c":"Referenced" },
    { "d":"A", "n":73, "x":12, "y":13, "a":"ATM", "c":"Source of quick cash, briefly" },
   
   
    { "d":"D", "n":1, "x":0, "y":0, "a":"AFG", "c":"Kabul's loc." },
    { "d":"D", "n":2, "x":1, "y":0, "a":"TAO", "c":"\"Way\" of some Asians" },
    { "d":"D", "n":3, "x":2, "y":0, "a":"EXO", "c":"Prefix meaning \"outside\"" },
    { "d":"D", "n":4, "x":4, "y":0, "a":"EGGS", "c":"Common recipe ingredients" },
    { "d":"D", "n":5, "x":5, "y":0, "a":"NORT", "c":"Hall-of-Fame college swimming coach ___ Thornton" },
    { "d":"D", "n":6, "x":6, "y":0, "a":"AFAR", "c":"Out yonder" },
    { "d":"D", "n":7, "x":7, "y":0, "a":"MADAMA", "c":"\"____ Butterfly\" (Puccini opera)" },
    { "d":"D", "n":8, "x":8, "y":0, "a":"IRE", "c":"Annoyance" },
    { "d":"D", "n":9, "x":10, "y":0, "a":"SECT", "c":"Religious splinter group" },
    { "d":"D", "n":10, "x":11, "y":0, "a":"TRAVEL", "c":"See the world" },
    { "d":"D", "n":11, "x":12, "y":0, "a":"RINDS", "c":"Orange leftovers" },
    { "d":"D", "n":12, "x":13, "y":0, "a":"IKEAS", "c":"Stores for DIY aficionados" },
    { "d":"D", "n":13, "x":14, "y":0, "a":"PARDO", "c":"Don of \"Saturday Night Live\"" },
    { "d":"D", "n":18, "x":3, "y":2, "a":"DAHL", "c":"Writer of \"The Landlady\"" },
    { "d":"D", "n":22, "x":0, "y":4, "a":"SCAPE", "c":"___goat" },
    { "d":"D", "n":24, "x":1, "y":4, "a":"HABER", "c":"Chemist who studied ammonia" },
    { "d":"D", "n":26, "x":2, "y":4, "a":"IBSEN", "c":"\"A Doll's House\" playwright" },
    { "d":"D", "n":27, "x":8, "y":4, "a":"ONECAN", "c":"Recipe amount" },
    { "d":"D", "n":28, "x":9, "y":4, "a":"INSITU", "c":"Undisturbed" },
    { "d":"D", "n":30, "x":4, "y":5, "a":"ECONO", "c":"Commercial prefix with Lodge" },
    { "d":"D", "n":31, "x":5, "y":5, "a":"CHROME", "c":"Google browser" },
    { "d":"D", "n":32, "x":6, "y":5, "a":"HANNAH", "c":"Philosopher Arendt" },
    { "d":"D", "n":33, "x":10, "y":5, "a":"EPSOM", "c":"Type of salts used in a bath" },
    { "d":"D", "n":36, "x":12, "y":6, "a":"LORRE", "c":" of \"Casablanca\"" },
    { "d":"D", "n":37, "x":13, "y":6, "a":"BYEAR", "c":"How some  music (2 words)" },
    { "d":"D", "n":40, "x":14, "y":6, "a":"JELLO", "c":"Sick person's " },
    { "d":"D", "n":42, "x":3, "y":9, "a":"REUBEN", "c":"Deli " },
    { "d":"D", "n":45, "x":7, "y":9, "a":"NELLIE", "c":"Nervous 's name" },
    { "d":"D", "n":47, "x":11, "y":9, "a":"EAST", "c":"The right ?" },
    { "d":"D", "n":50, "x":0, "y":10, "a":"AARON", "c":" name" },
    { "d":"D", "n":52, "x":1, "y":10, "a":"SLURS", "c":"" },
    { "d":"D", "n":54, "x":2, "y":10, "a":"MOMMY", "c":"Daddy's " },
    { "d":"D", "n":55, "x":4, "y":11, "a":"DARC", "c":" ___ (French saint)" },
    { "d":"D", "n":57, "x":8, "y":11, "a":"IOTA", "c":"Smidgen" },
    { "d":"D", "n":58, "x":9, "y":11, "a":"MOET", "c":"Dom  maker" },
    { "d":"D", "n":59, "x":10, "y":11, "a":"ODDS", "c":"77, 183, and " },
    { "d":"D", "n":60, "x":6, "y":12, "a":"BCS", "c":"deg." },
    { "d":"D", "n":61, "x":12, "y":12, "a":"YAY", "c":"'Huzzah!'" },
    { "d":"D", "n":63, "x":13, "y":12, "a":"PTO", "c":"Local school ." },
    { "d":"D", "n":64, "x":14, "y":12, "a":"EMU", "c":"Aussie"},
    { "d":"D", "n":67, "x":14, "y":12, "a":"EMU", "c":"Aussie" }
  ]
}
